// <auto-generated />
using GreenThump.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThump.Migrations
{
    [DbContext(typeof(GreenThumpDb))]
    [Migration("20231204105107_Change_instrcution")]
    partial class Change_instrcution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenThump.Models.Instruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InstructionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instructions");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("instructions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstructionText = "Allow soil to dry between waterings.",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 2,
                            InstructionText = "Avoid overwatering.",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 3,
                            InstructionText = "Keep soil consistently moist but not soggy.",
                            PlantId = 2
                        },
                        new
                        {
                            Id = 4,
                            InstructionText = "Water when the top inch of soil feels dry.",
                            PlantId = 2
                        },
                        new
                        {
                            Id = 5,
                            InstructionText = " Allow the soil to dry out between waterings.",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 6,
                            InstructionText = "Water sparingly.",
                            PlantId = 3
                        });
                });

            modelBuilder.Entity("GreenThump.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sansevieria"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spathiphyllum"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zamioculcas"
                        });
                });

            modelBuilder.Entity("GreenThump.Models.Instruction", b =>
                {
                    b.HasOne("GreenThump.Models.Plant", "Plant")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThump.Models.Plant", b =>
                {
                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
