// <auto-generated />
using GreenThump.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumb.Migrations
{
    [DbContext(typeof(GreenThumbDb))]
    partial class GreenThumbDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenThump.Models.Instruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InstructionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("instructions");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("instructions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstructionText = "Let soil dry.",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 2,
                            InstructionText = "Avoid overwatering.",
                            PlantId = 1
                        },
                        new
                        {
                            Id = 3,
                            InstructionText = "Keep soil moist.",
                            PlantId = 2
                        },
                        new
                        {
                            Id = 4,
                            InstructionText = "Water when top dry.",
                            PlantId = 2
                        },
                        new
                        {
                            Id = 5,
                            InstructionText = " Let soil dry then water.",
                            PlantId = 3
                        },
                        new
                        {
                            Id = 6,
                            InstructionText = "Water sparingly.",
                            PlantId = 3
                        });
                });

            modelBuilder.Entity("GreenThump.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sansevieria plants are characterized by their long, upright, and sword-shaped leaves",
                            Name = "Sansevieria"
                        },
                        new
                        {
                            Id = 2,
                            Description = "commonly known as peace lilies, is a genus of flowering plants in the family Araceae. ",
                            Name = "Spathiphyllum"
                        },
                        new
                        {
                            Id = 3,
                            Description = "is a popular and hardy indoor plant known for its tolerance of low light conditions",
                            Name = "Zamioculcas"
                        });
                });

            modelBuilder.Entity("GreenThump.Models.Instruction", b =>
                {
                    b.HasOne("GreenThump.Models.Plant", "Plant")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThump.Models.Plant", b =>
                {
                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
